### ISSUE TITLE
Cannot modify properties of WrappedNative

### ISSUE THREAD

**Issue by GLStephen** [alechill/livevalidation#1]
I get this when validating some text fields in my Application:

Error: uncaught exception: [Exception... "Cannot modify properties of a WrappedNative"  nsresult: "0x80570034 (NS_ERROR_XPC_CANT_MODIFY_PROP_ON_WN)"  location: "JS frame :: chrome://global/content/bindings/autocomplete.xml :: onxblpopuphiding :: line 825"  data: no]

**Comment by alechill** [comment]
Issue is a bug in Mozilla Firefox autocomplete ( see https://bugzilla.mozilla.org/show_bug.cgi?id=428602 )

**Comment by GLStephen** [comment]
Thanks. Good to know. You've got a closed bug on GitHub now. Do you get a badge?
